#!/bin/bash
cd ../../..

# The path of vswhere is hard coded in Visual Studio Installer's installer, it should always be here. 
VSWHERE="C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe"
if [ ! -f "$VSWHERE" ]; then
  echo "ERROR: vswhere.exe not found at expected location: $VSWHERE"
  read -N 1
fi

# Run vswhere to get the installation path
INSTALLATION_PATH=$("$VSWHERE" -property installationPath)

# Find msbuild.exe
MSBUILD_PATH="$INSTALLATION_PATH/MSBuild/Current/Bin/msbuild.exe"

# Check if msbuild.exe exists
if [ ! -f "$MSBUILD_PATH" ]; then
  echo "ERROR: msbuild.exe not found at expected location: $MSBUILD_PATH"
  read -N 1
fi

echo "$MSBUILD_PATH"
cmd //c "$PWD/Build.bat" "$MSBUILD_PATH"

