#!/bin/bash
cd ../../..

# The path of vswhere is hard coded in Visual Studio Installer's installer, it should always be here. 
VSWHERE="C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe"
if [ ! -f "" ]; then
  echo "ERROR: vswhere.exe not found at expected location: "
  read -N 1
fi

# Run vswhere to get the installation path
INSTALLATION_PATH=

# Find msbuild.exe
MSBUILD_PATH="/MSBuild/Current/Bin/msbuild.exe"

# Check if msbuild.exe exists
if [ ! -f "" ]; then
  echo "ERROR: msbuild.exe not found at expected location: "
  read -N 1
fi

echo ""
./Build.bat ""

