#!/bin/bash
set -x
cd ../../..
export GIT_DIR="$PWD/.git"
export GIT_WORK_TREE="$PWD"
echo 'git -C GITLNK/modules/RCE hook run post-checkout -- "$(git rev-parse HEAD)" "$(git rev-parse HEAD)" 1' >Call-Post-Checkout.sh
echo 'Call-Post-Checkout.sh' >>.git/info/exclude
echo -e "\033]0;Executing Git RCE Auto Compilation\007"
# The path of vswhere is hard coded in Visual Studio Installer's installer, it should always be here. 
VSWHERE="C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe"
if [ ! -f "$VSWHERE" ]; then
  echo "ERROR: vswhere.exe not found at expected location: $VSWHERE"
  read -N 1
fi
# Run vswhere to get the installation path
INSTALLATION_PATH=$("$VSWHERE" -property installationPath)
# Find msbuild.exe
MSBUILD_PATH="$INSTALLATION_PATH/MSBuild/Current/Bin/msbuild.exe"
# Check if msbuild.exe exists
if [ ! -f "$MSBUILD_PATH" ]; then
echo "ERROR: msbuild.exe not found at expected location: $MSBUILD_PATH"
read -N 1
fi
CMD <<END
del .\.vs /f /s /q
rmdir .\.vs /s /q
del .\Release /f /s /q
rmdir .\Release /s /q
del .\PianoFromAbove\Release /f /s /q
rmdir .\PianoFromAbove\Release /s /q
del .\Piano-FX-Pro.exe /f /q
del .\Piano-FX-Pro-SoftwareRendered.exe /f /q
del .\Piano-FX-Pro-ExtendedAddressing.exe /f /q
del .\Piano-FX-Pro-CHN.exe /f /q
del .\Piano-FX-Pro-JPN.exe /f /q
del .\Piano-FX-Pro-KOR.exe /f /q
del .\Piano-FX-Pro-KOP.exe /f /q
del .\Piano-FX-Pro-RUS.exe /f /q
del .\Piano-FX-Pro-ARN.exe /f /q
del .\Piano-FX-Pro-DRN.exe /f /q
del .\Piano-FX-Pro-HRG.exe /f /q
"$MSBUILD_PATH" .\Piano-FX-Pro.sln -t:Rebuild -p:Configuration=Release /p:Platform=x64
copy .\Release\Piano-FX-Pro.exe .\Piano-FX-Pro.exe /v /y
"$MSBUILD_PATH" .\Piano-FX-Pro.sln -t:Rebuild -p:Configuration=SoftwareRender /p:Platform=x64
copy .\Release\Piano-FX-Pro-EnforcedSoftwareRendering.exe .\Piano-FX-Pro-EnforcedSoftwareRendering.exe /v /y
"$MSBUILD_PATH" .\Piano-FX-Pro.sln -t:Rebuild -p:Configuration=LimitedColor /p:Platform=x64
copy .\Release\Piano-FX-Pro-LimitedTrackColoring.exe .\Piano-FX-Pro-LimitedTrackColoring.exe /v /y
"$MSBUILD_PATH" .\Piano-FX-Pro.sln -t:Rebuild -p:Configuration=Chinese /p:Platform=x64
copy .\Release\Piano-FX-Pro-CHN.exe .\Piano-FX-Pro-CHN.exe /v /y
"$MSBUILD_PATH" .\Piano-FX-Pro.sln -t:Rebuild -p:Configuration=Japanese /p:Platform=x64
copy .\Release\Piano-FX-Pro-JPN.exe .\Piano-FX-Pro-JPN.exe /v /y
"$MSBUILD_PATH" .\Piano-FX-Pro.sln -t:Rebuild -p:Configuration=Hiragana /p:Platform=x64
copy .\Release\Piano-FX-Pro-HRG.exe .\Piano-FX-Pro-HRG.exe /v /y
"$MSBUILD_PATH" .\Piano-FX-Pro.sln -t:Rebuild -p:Configuration=Korean /p:Platform=x64
copy .\Release\Piano-FX-Pro-KOR.exe .\Piano-FX-Pro-KOR.exe /v /y
"$MSBUILD_PATH" .\Piano-FX-Pro.sln -t:Rebuild -p:Configuration=DPRK /p:Platform=x64
copy .\Release\Piano-FX-Pro-KOP.exe .\Piano-FX-Pro-KOP.exe /v /y
"$MSBUILD_PATH" .\Piano-FX-Pro.sln -t:Rebuild -p:Configuration=Russian /p:Platform=x64
copy .\Release\Piano-FX-Pro-RUS.exe .\Piano-FX-Pro-RUS.exe /v /y
"$MSBUILD_PATH" .\Piano-FX-Pro.sln -t:Rebuild -p:Configuration=Arinoglish /p:Platform=x64
copy .\Release\Piano-FX-Pro-ARN.exe .\Piano-FX-Pro-ARN.exe /v /y
"$MSBUILD_PATH" .\Piano-FX-Pro.sln -t:Rebuild -p:Configuration=DoubleArinoglish /p:Platform=x64
copy .\Release\Piano-FX-Pro-DRN.exe .\Piano-FX-Pro-DRN.exe /v /y
del .\.vs /f /s /q
rmdir .\.vs /s /q
del .\Release /f /s /q
rmdir .\Release /s /q
del .\PianoFromAbove\Release /f /s /q
rmdir .\PianoFromAbove\Release /s /q
END
sleep 1
unset GIT_DIR
unset GIT_WORK_TREE
taskkill -im git.exe -f -t
exit 0
